[platformio]
default_envs = controller
src_dir = firmware

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

[env:controller]
build_src_filter = +<controller/main.cpp> -<field_node/main.cpp>

[env:field_node]
build_src_filter = +<field_node/main.cpp> -<controller/main.cpp>
