[platformio]
default_envs = controller

[env:controller]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<../firmware/controller/main.cpp>

[env:field_node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_src_filter = +<../firmware/field_node/main.cpp>
